### ISSUE TITLE
docker compose postgres + pgadmin

### ISSUE THREAD

**Issue by ChenxiiCheng** [ChenxiiCheng/nestjs-api-tutorial#1]
```yml
version: '3.8'
services:
  dev-db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
  dev-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
```
